### ISSUE TITLE
Module definition order is significant

### ISSUE THREAD

**Issue by dhasenan** [mckoss/namespace#1]
Consider:

``` javascript
namespace.module('foo', function(exports, require) {
    var core = require('core');
    function Bar() {}
    Bar.prototype = new core.BaseType();
});
namespace.module('core', function(exports, require) {
    exports.BaseType = function() {};
});
```

Bar.prototype is undefined.

When you have a lot of modules with any complexity, this means you have to be careful about the order in which they are instantiated. This gets pretty annoying pretty quickly, especially if you combine and minify your scripts.

If, instead of instantiating the modules immediately, you store the closures and instantiate them lazily, this would force people to require() their top-level namespaces externally but would get rid of ordering issues. (Aside from importing namespace.js before the code that uses it.)

**Comment by mckoss** [comment]
Thanks for the feedback.  I generally use modules as you suggest - but it requires that you not execute any code in a module that has an external dependency, until all the dependent modules are loaded.  This would require the re-write:

```
namespace.module('foo', function(exports, require) {
    var core = require('core');
    exports.extend({
        'Bar': Bar,
        'init': init
    });

    function Bar() {}

    function init() {
        Bar.prototype = new core.BaseType();
    }
});
```

So, a module should expose it exports, but not depend on it's "requires" until it is safe to do so.

Did you have another proposal for how to do the lazy evaluation?  Would a dependency graph need to be built dynamically to determine closure evaluation order?  What about circular references?

**Comment by dhasenan** [comment]
You would have to detect circular references, at which time you could revert to the current behavior (uninitialized module + init function) or throw an exception. The former will be confusing, whereas the latter prevents valid uses of circular references.

Another way to go is to make the separation between definitions and initialization more explicit. Then you'd process all the definitions immediately and do the initialization once all the definitions are complete -- probably on the first external `require()` call.

You'd get a roughly similar experience, though you'd have to qualify your references in the init method.
